Repository Gongjakso/Gongjakso_web, pull requests merged in 2024-05, with the labels that each got.

#163 🔀 Feat/mainPageAnimation#158
  gongjakso/src/pages/HomePage/HomePage.jsx
  gongjakso/src/pages/HomePage/ScrollHandler.jsx
  gongjakso/src/pages/HomePage/TopButton.Styled.jsx
  gongjakso/src/pages/HomePage/TopButton.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#167 🔀 Refactor/fixAPI#165 [API 전체 수정 및 UI 추가]
  gongjakso/src/features/modal/ApplyModal.jsx
  gongjakso/src/features/modal/ApplyModal.styled.jsx
  gongjakso/src/features/modal/ClickApply.jsx
  gongjakso/src/features/modal/ClickmyApply.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx
  gongjakso/src/service/apply_service.js
  gongjakso/src/service/post_service.js
Labels: 🙆🏻‍♀️ 구현 완료, ♻️리팩토링, ✨기능 추가

#170 🔀 Refactor/fixPost#169 [스타일 수정]
  gongjakso/src/features/modal/ClickApply.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
  gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#172 🔀 Refactor/AppliedTeamBoxApi#164
  gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx
  gongjakso/src/pages/TeamBox/TeamBox.jsx
  gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
Labels: 🐛버그 수정, 🙆🏻‍♀️ 구현 완료

#176 🔀 Feat/scrapPage#166 [스크랩 페이지 API 연결]
  gongjakso/src/components/Header/Bubble.jsx
  gongjakso/src/pages/HomePage/HomePage.jsx
  gongjakso/src/pages/HomePage/ScrollHandler.jsx
  gongjakso/src/pages/ProfileRecruited/RecruitedTeam.jsx
  gongjakso/src/pages/ScrapPage/Scrap.Styled.jsx
  gongjakso/src/pages/ScrapPage/Scrap.jsx
  gongjakso/src/service/profile_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#178 🔀 Fix/TotalStyleAPI1#171 [스타일 크기 조정]
  gongjakso/src/features/modal/ApplyCancel.jsx
  gongjakso/src/features/modal/ApplyModal.jsx
  gongjakso/src/features/modal/ApplyModal.styled.jsx
  gongjakso/src/features/modal/ClickApply.jsx
  gongjakso/src/features/modal/ClickmyApply.jsx
  gongjakso/src/features/modal/Completed.jsx
  gongjakso/src/features/modal/MyPageTeam.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
  gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
  gongjakso/src/service/apply_service.js
Labels: 🙆🏻‍♀️ 구현 완료, ✨기능 추가

#181 🔀 Refactor/LoginModal#177
  gongjakso/src/components/Auth/KakaoRedirectPage.Styled.jsx
  gongjakso/src/components/Auth/KakaoRedirectPage.jsx
  gongjakso/src/components/Header/Bubble.Styled.jsx
  gongjakso/src/components/Header/Bubble.jsx
  gongjakso/src/components/common/Input/infoDrop.styled.jsx
  gongjakso/src/features/modal/Modal.Styled.jsx
  gongjakso/src/features/modal/SignUpModal.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#189 🔀 Fix/ErrorCheck#184 [API 반영 및 추가]
  gongjakso/src/assets/images/postLink.svg
  gongjakso/src/features/modal/ApplyModal.jsx
  gongjakso/src/features/modal/ClickApply.jsx
  gongjakso/src/features/modal/ClickmyApply.jsx
  gongjakso/src/features/modal/Completed.jsx
  gongjakso/src/features/modal/MyPageTeam.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
  gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/service/post_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#187 🔀Refactor/portfolioUI#182
  gongjakso/src/pages/Portfolio/MyPortfolio.jsx
  gongjakso/src/pages/Portfolio/MyPortfolioStyled.jsx
  gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#195 🔀 Fix/LoginError#193
  gongjakso/src/components/Auth/KakaoRedirectPage.jsx
  gongjakso/src/pages/ScrapPage/Scrap.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#191 🔀Refactor/mypageAppliedApi#183
  gongjakso/src/pages/Portfolio/MyPortfolio.jsx
  gongjakso/src/pages/Portfolio/MyPortfolioStyled.jsx
  gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx
  gongjakso/src/pages/TeamBox/TeamBox.jsx
  gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
  gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx
  gongjakso/src/service/profile_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#196 🔀 Fix/NewScrap#194 [변경된 API 변수 반영 완료]
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
Labels: 🙆🏻‍♀️ 구현 완료
