Repository Gongjakso/Gongjakso_web, pull requests merged in 2024-02, with the labels that each got.

#36 🔀Feat/teamBoxUI#30
  gongjakso/src/assets/images/Edit.svg
  gongjakso/src/assets/images/Up.svg
  gongjakso/src/pages/Portfolio/MyPortfolio.jsx
  gongjakso/src/pages/Portfolio/MyPortfolioStyled.jsx
  gongjakso/src/pages/ProfileInfo/MyInfo.jsx
  gongjakso/src/pages/ProfileInfo/MyInfoStyled.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx
  gongjakso/src/pages/TeamBox/TeamBox.jsx
  gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
Labels: 🙆🏻‍♀️ 구현 완료, 🙏 PR 중..

#39 🔀 Feat/teamBuildPageUI#5 [UI] 구현
  gongjakso/package-lock.json
  gongjakso/package.json
  gongjakso/src/assets/images/TeamBuildIcon.svg
  gongjakso/src/components/common/Calendar/SelectCalendar.Styled.jsx
  gongjakso/src/components/common/Calendar/SelectCalendar.jsx
  gongjakso/src/components/common/CountGuest/CountGuest.Styled.jsx
  gongjakso/src/components/common/CountGuest/CountGuest.jsx
  gongjakso/src/components/common/Input/Input.Styled.jsx
  gongjakso/src/pages/TeamBuildPage/TeamBuildPage.Styled.jsx
  gongjakso/src/pages/TeamBuildPage/TeamBuildPage.jsx
  gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.Styled.jsx
  gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx
  gongjakso/yarn.lock
Labels: 🥸구현 중..

#38 🔀 Feat/loginPageUI#23
  gongjakso/.gitignore
  gongjakso/src/components/Auth/KakaoRedirectPage.Styled.jsx
  gongjakso/src/components/Auth/KakaoRedirectPage.jsx
  gongjakso/src/components/Auth/Login.Styled.jsx
  gongjakso/src/components/Auth/Login.jsx
  gongjakso/src/router/Router.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#44 🔀 Feat/mainPageBannerUI#37
  gongjakso/src/pages/HomePage/Banner.Styled.jsx
  gongjakso/src/pages/HomePage/Banner.jsx
  gongjakso/src/pages/HomePage/HomePage.Styled.jsx
  gongjakso/src/pages/HomePage/HomePage.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#45 🔀 Feat/profileTeamUI#34
  gongjakso/src/features/modal/ApplyModal.jsx
  gongjakso/src/features/modal/ApplyModal.styled.jsx
  gongjakso/src/features/modal/ClickApply.jsx
  gongjakso/src/features/modal/Completed.jsx
  gongjakso/src/features/modal/MyPageTeam.jsx
  gongjakso/src/features/modal/Roundform.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx
  gongjakso/src/pages/ProfileRecruit/UserData.jsx
  gongjakso/src/styles/theme.js
Labels: 🙆🏻‍♀️ 구현 완료

#48 🔀 Feat/teamBoxUI#30
  .DS_Store
  gongjakso/src/assets/images/ArrowDetail.svg
  gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx
  gongjakso/src/pages/TeamBox/TeamBox.jsx
  gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#41 🔀 Feat/profileParticipatedTeamUI#40
  gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx
  gongjakso/src/pages/ProfileParticipated/ParticipatedTeamStyled.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#52 🔀 Fix/editApplyModalUI#49 [레이아웃, 폰트 조정]
  gongjakso/src/features/modal/ApplyModal.jsx
  gongjakso/src/features/modal/ApplyModal.styled.jsx
  gongjakso/src/features/modal/ClickApply.jsx
  gongjakso/src/features/modal/Completed.jsx
  gongjakso/src/features/modal/MyPageTeam.jsx
  gongjakso/src/features/modal/Roundform.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#51 🔀Feat/postPageUI#43 [UI]
  gongjakso/package-lock.json
  gongjakso/package.json
  gongjakso/src/assets/images/banner.svg
  gongjakso/src/components/Header/Buttons.jsx
  gongjakso/src/components/Pagination/Pagination.jsx
  gongjakso/src/components/SwiperBanner/SwiperBanner.Styled.jsx
  gongjakso/src/components/SwiperBanner/SwiperBanner.jsx
  gongjakso/src/components/common/Input/Input.Styled.jsx
  gongjakso/src/components/common/Input/Input.jsx
  gongjakso/src/pages/PostMainPage/PostMainPage.Styled.jsx
  gongjakso/src/pages/PostMainPage/PostMainPage.jsx
  gongjakso/src/router/Router.jsx
  gongjakso/yarn.lock
Labels: 🙆🏻‍♀️ 구현 완료

#57 🔀 Fix/profilePageUI#53
  gongjakso/src/pages/Portfolio/MyPortfolio.jsx
  gongjakso/src/pages/Portfolio/MyPortfolioStyled.jsx
  gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx
  gongjakso/src/pages/ProfileApplied/AppliedTeamStyled.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx
  gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx
  gongjakso/src/pages/ProfileParticipated/ParticipatedTeamStyled.jsx
  gongjakso/src/pages/TeamBox/TeamBox.jsx
  gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#56 🔀 Fix/editMainPageUI#55
  gongjakso/src/pages/HomePage/HomePage.Styled.jsx
  gongjakso/src/styles/theme.js
Labels: 🙆🏻‍♀️ 구현 완료

#60 🔀 Fix/editProfileRecruitUI#54 [UI 수정]
  gongjakso/src/features/modal/ClickApply.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx
  gongjakso/src/pages/ProfileRecruit/UserData.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#62 🔀 Fix/profileMyInfoUI#59
  gongjakso/src/pages/ProfileInfo/MyInfo.jsx
  gongjakso/src/pages/ProfileInfo/MyInfoStyled.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/router/Router.jsx
  gongjakso/src/utils/jobData.json
  gongjakso/src/utils/majorData.json
Labels: 🙆🏻‍♀️ 구현 완료

#65 🔀Refactor/editAllLayout#63 [UI] 전체적인 레이아웃, 스타일 수정
  gongjakso/src/Layout/DefaultLayout.jsx
  gongjakso/src/Layout/DefaultLayout.styled.jsx
  gongjakso/src/Layout/NoHeaderLayout.jsx
  gongjakso/src/assets/mapData/mapData.json
  gongjakso/src/components/common/Input/Input.Styled.jsx
  gongjakso/src/components/common/Input/Input.jsx
  gongjakso/src/features/modal/Modal.Styled.jsx
  gongjakso/src/features/modal/SignUpModal.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx
  gongjakso/src/pages/ProfileRecruit/UserData.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#70 🔀 Fix/editPagesStyle#61 [UI] 수정
  gongjakso/src/pages/CalendarPage/Calendar.jsx
  gongjakso/src/pages/CalendarPage/Calendar.styled.jsx
  gongjakso/src/pages/CalendarPage/data/contestData.js
  gongjakso/src/pages/CalendarPage/data/projectData.js
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
  gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#73 🔀 Fix/EditLoginModalUI#58
  gongjakso/src/features/modal/LoginModal1.jsx
  gongjakso/src/features/modal/LoginModal2.jsx
  gongjakso/src/features/modal/Modal.Styled.jsx
  gongjakso/src/features/modal/SignUpModal.jsx
  gongjakso/src/pages/HomePage/HomePage.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#77 🔀 Feat/FooterLink#74
  gongjakso/src/components/Footer/Footer.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#80 🔀 Fix/editMainPageUI#75
  gongjakso/src/assets/images/calendar.png
  gongjakso/src/pages/HomePage/Banner.Styled.jsx
  gongjakso/src/pages/HomePage/Banner.jsx
  gongjakso/src/pages/HomePage/HomePage.Styled.jsx
  gongjakso/src/pages/HomePage/HomePage.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#83 🔀 Feat/editMainPageBannerApi#79 [API] 구현
  gongjakso/src/components/Header/Buttons.jsx
  gongjakso/src/components/SwiperBanner/SwiperBanner.Styled.jsx
  gongjakso/src/components/SwiperBanner/SwiperBanner.jsx
  gongjakso/src/pages/PostMainPage/PostMainPage.jsx
Labels: ✨기능 추가

#87 🔀Feat/postTeamBuildingApi#86 [API]
  gongjakso/src/components/common/Calendar/SelectCalendar.Styled.jsx
  gongjakso/src/components/common/CountGuest/CountGuest.Styled.jsx
  gongjakso/src/components/common/Input/Input.Styled.jsx
  gongjakso/src/components/common/Input/Input.jsx
  gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.Styled.jsx
  gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx
  gongjakso/src/service/post_service.js
Labels: ✨기능 추가

#89 🔀 Feat/RecruitBtnAPI#78 [API]
  gongjakso/src/features/modal/ApplyModal.jsx
  gongjakso/src/features/modal/ApplyModal.styled.jsx
  gongjakso/src/features/modal/ClickApply.jsx
  gongjakso/src/features/modal/Completed.jsx
  gongjakso/src/features/modal/MyPageTeam.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx
  gongjakso/src/service/apply_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#93 🔀 Feat/PostDetailPageAPI#91 [API]
  gongjakso/src/features/modal/ApplyModal.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageData.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
  gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
  gongjakso/src/service/post_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#99 🔀 Fix/HeaderUI#97
  gongjakso/src/components/Header/Buttons.jsx
  gongjakso/src/components/Header/Header.Styled.jsx
  gongjakso/src/components/Header/Header.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#101 🔀 Fix/RecruitAPI#95 [API]
  gongjakso/src/features/modal/MyPageTeam.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/service/apply_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#102 🔀 Feat/AddScrapAPI#96 [API]
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
  gongjakso/src/service/post_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#92 🔀Feat/profileApi#64
  gongjakso/src/assets/images/CloseWhite.svg
  gongjakso/src/pages/Portfolio/MyPortfolio.jsx
  gongjakso/src/pages/Portfolio/MyPortfolioStyled.jsx
  gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx
  gongjakso/src/pages/ProfileInfo/MyInfo.jsx
  gongjakso/src/pages/ProfileInfo/MyInfoStyled.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx
  gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx
  gongjakso/src/pages/TeamBox/TeamBox.jsx
  gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
  gongjakso/src/service/profile_service.js
Labels: 🥸구현 중..

#105 🔀 Feat/CalendarRecruitAPI#94 [API]
  gongjakso/src/features/modal/ApplyModal.jsx
  gongjakso/src/features/modal/ClickApply.jsx
  gongjakso/src/pages/CalendarPage/Calendar.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.styled.jsx
  gongjakso/src/service/apply_service.js
  gongjakso/src/service/calendar_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#104 🔀 Fix/editDropdownUI#103
  gongjakso/src/components/common/Input/Input.Styled.jsx
  gongjakso/src/components/common/Input/Input.jsx
  gongjakso/src/pages/PostMainPage/PostMainPage.Styled.jsx
  gongjakso/src/pages/PostMainPage/PostMainPage.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#108 🔀 Feat/profileApi#64
  gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#110 🔀 Fix/editCalendarAPI#106
  gongjakso/src/index.js
  gongjakso/src/pages/CalendarPage/Calendar.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#111 🔀 Fix/FinalPostDetailUI#109 [UI]
  gongjakso/src/pages/CalendarPage/Calendar.jsx
  gongjakso/src/pages/CalendarPage/data/contestData.js
  gongjakso/src/pages/CalendarPage/data/projectData.js
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#115 🔀 Fix/RecruitState#112
  gongjakso/src/features/modal/ClickApply.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/pages/ProfileRecruit/UserData.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#127 🔀 Refactor/PostMainpage#122
  gongjakso/src/components/common/Input/Input.Styled.jsx
  gongjakso/src/components/common/Input/Multilevel.styled.jsx
  gongjakso/src/features/modal/ApplyModal.jsx
  gongjakso/src/features/modal/ApplyModal.styled.jsx
  gongjakso/src/features/modal/Completed.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
  gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
  gongjakso/src/pages/PostMainPage/PostMainPage.Styled.jsx
  gongjakso/src/pages/PostMainPage/PostMainPage.jsx
  gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#126 🔀 Refactor/PostdetailPage#121
  gongjakso/src/features/modal/ApplyModal.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#124 🔀 Refactor/Header#123
  gongjakso/src/assets/images/logo.png
  gongjakso/src/assets/images/logo.svg
  gongjakso/src/components/Header/Header.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#130 🔀 Refactor/Footer#128
  gongjakso/src/components/Footer/Footer.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#132 🔀 Refactor/RecruitPageID#131
  gongjakso/src/features/modal/ClickApply.jsx
  gongjakso/src/features/modal/MyPageTeam.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#137 🔀 Refactor/AllpageStyle#133
  gongjakso/src/components/Header/Buttons.styled.jsx
  gongjakso/src/components/Header/Header.Styled.jsx
  gongjakso/src/components/common/Calendar/SelectCalendar.Styled.jsx
  gongjakso/src/components/common/CountGuest/CountGuest.Styled.jsx
  gongjakso/src/components/common/Input/Input.Styled.jsx
  gongjakso/src/features/modal/ApplyModal.jsx
  gongjakso/src/pages/CalendarPage/Calendar.styled.jsx
  gongjakso/src/pages/HomePage/HomePage.Styled.jsx
  gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx
  gongjakso/src/pages/TeamBuildPage/TeamBuildPage.Styled.jsx
  gongjakso/src/pages/TeamBuildPage/TeamBuildPage.jsx
  gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.Styled.jsx
  gongjakso/src/pages/TeamBuildPage/TeamBuildingUploadPage.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#135 🔀 Fix/DropStyle#134 [API]
  gongjakso/src/components/common/Input/Multilevel.jsx
  gongjakso/src/components/common/Input/Multilevel.styled.jsx
Labels: 🙆🏻‍♀️ 구현 완료
