Repository Gongjakso/Gongjakso_web, pull requests merged in 2024-09, with the labels that each got.

#230 🔀 Feat/PortFolioAPI#218 [포트폴리오 입력페이지 구현]
  gongjakso/package-lock.json
  gongjakso/package.json
  gongjakso/src/assets/images/calendaremoji.svg
  gongjakso/src/assets/images/checked.svg
  gongjakso/src/assets/images/deleteIcon.svg
  gongjakso/src/assets/images/editIcon.svg
  gongjakso/src/assets/images/unchecked.svg
  gongjakso/src/components/Header/Bubble.Styled.jsx
  gongjakso/src/components/common/Calendar/SelectOne.Styled.jsx
  gongjakso/src/components/common/Calendar/SelectOne.jsx
  gongjakso/src/components/common/Input/Input.Styled.jsx
  gongjakso/src/components/common/Input/infoDrop.styled.jsx
  gongjakso/src/features/modal/DeleteModal.jsx
  gongjakso/src/features/modal/PortfolioModal.Styled.jsx
  gongjakso/src/pages/Portfolio/MakePortfolio.jsx
  gongjakso/src/pages/Portfolio/Portfolio.Styled.jsx
  gongjakso/src/pages/Portfolio/UsePortfolio.jsx
  gongjakso/src/pages/ProfileInfo/MyInfoStyled.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx
  gongjakso/src/router/Router.jsx
  gongjakso/src/service/portfolio_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#232 🔀 Feat/mainPageBtn#231 [메인페이지 버튼 기능추가]
  gongjakso/src/pages/HomePage/HomePage.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#235 🔀 Feat/PostDetailAPI#228 [공고 상세페이지 및 지원하기 API]
  gongjakso/src/features/modal/ApplyModal.styled.jsx
  gongjakso/src/features/modal/Completed.jsx
  gongjakso/src/pages/ContestDetailPage/ContestDetailPage.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/router/Router.jsx
  gongjakso/src/service/apply_service.js
  gongjakso/src/service/post_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#237 🔀 Feat/UserDetailPageAPI#236 [사용자 상태 별 공고상세페이지 API]
  gongjakso/src/features/modal/ApplyCancel.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
  gongjakso/src/service/apply_service.js
  gongjakso/src/service/post_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#238 🔀 Feat/ExistPortfolio#233
  gongjakso/src/pages/ContestDetailPage/ContestDetailPage.Styled.jsx
  gongjakso/src/pages/ContestListBox/ContestListBox.Styled.jsx
  gongjakso/src/pages/ContestListBox/ContestListBox.jsx
  gongjakso/src/pages/Portfolio/MakePortfolio.jsx
  gongjakso/src/pages/Portfolio/Portfolio.Styled.jsx
  gongjakso/src/pages/Portfolio/UsePortfolio.jsx
  gongjakso/src/pages/PostMainPage/PostMainPage.Styled.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx
  gongjakso/src/pages/TeamBox/TeamBox.jsx
  gongjakso/src/router/Router.jsx
  gongjakso/src/service/portfolio_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#242 🔀 Refactor/PostDetailPagefinal#241 [공고 상세페이지 최종]
  gongjakso/src/features/modal/ApplyCancel.jsx
  gongjakso/src/features/modal/ApplyModal.styled.jsx
  gongjakso/src/features/modal/Completed.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
  gongjakso/src/service/post_service.js
Labels: ♻️리팩토링

#243 🔀 Fix/Portfolio#239 [포트폴리오 오류 수정]
  gongjakso/src/pages/Portfolio/MakePortfolio.jsx
  gongjakso/src/pages/Portfolio/Portfolio.Styled.jsx
  gongjakso/src/pages/Portfolio/UsePortfolio.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx
  gongjakso/src/service/portfolio_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#245 🔀 Feat/myRecruitPageAPI#219
  gongjakso/src/pages/Portfolio/Portfolio.Styled.jsx
  gongjakso/src/pages/Portfolio/UsePortfolio.jsx
  gongjakso/src/pages/ProfileApplied/AppliedTeam.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/pages/ProfileRecruited/RecruitedTeam.jsx
  gongjakso/src/pages/ScrapPage/Scrap.jsx
  gongjakso/src/pages/TeamBox/TeamBox.jsx
  gongjakso/src/service/apply_service.js
  gongjakso/src/service/profile_service.js
Labels: 🙆🏻‍♀️ 구현 완료, ♻️리팩토링

#247 🔀 모집 취소 API 추가
  gongjakso/src/features/modal/MyPageTeam.jsx
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/service/apply_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#255 🔀 Refactor/ComponentSize#252 [메인페이지 컴포넌트 사이즈 수정]
  gongjakso/src/pages/HomePage/HomePage.Styled.jsx
Labels: 🙆🏻‍♀️ 구현 완료

#256 🔀 Refator/recruitButtomAPI#254 [API 구현]
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/service/apply_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#263 🔀 Refactor/PortfolioApi#259 [포트폴리오 로직 수정]
  gongjakso/src/features/modal/DeleteModal.jsx
  gongjakso/src/pages/HomePage/HomePage.Styled.jsx
  gongjakso/src/pages/Portfolio/UsePortfolio.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/service/portfolio_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#266 🔀 Feat/PostpageMyApply#262 [나의 지원서보기 임시 모달 추가]
  gongjakso/src/features/modal/ApplyModal.styled.jsx
  gongjakso/src/features/modal/ClickmyApply.jsx
  gongjakso/src/features/modal/Completed.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/service/apply_service.js
  gongjakso/src/service/post_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#267 🔀Feat/recruitStateAPI#265
  gongjakso/src/pages/ProfileRecruit/ProfileRecruit.jsx
  gongjakso/src/service/apply_service.js
Labels: 🙆🏻‍♀️ 구현 완료

#273 🔀 Fix/PortfolioApi#270 [포트폴리오 오류 수정]
  gongjakso/src/pages/Portfolio/MakePortfolio.jsx
  gongjakso/src/pages/Portfolio/UsePortfolio.jsx
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
Labels: 🐛버그 수정, 🙆🏻‍♀️ 구현 완료
