Repository Gongjakso/Gongjakso_web, pull requests merged in 2024-10, with the labels that each got.

#291 🔀 Refactor/profilePage#290
  gongjakso/src/pages/ProfilePage/ProfilePage.jsx
  gongjakso/src/pages/ProfilePage/ProfilePageStyled.jsx
  gongjakso/src/pages/ProfileParticipated/ParticipatedTeam.jsx
  gongjakso/src/pages/ProfileParticipated/ParticipatedTeamStyled.jsx
  gongjakso/src/pages/ProfileRecruited/RecruitedTeam.Styled.jsx
  gongjakso/src/pages/ProfileRecruited/RecruitedTeam.jsx
  gongjakso/src/pages/ScrapPage/Scrap.Styled.jsx
  gongjakso/src/pages/ScrapPage/Scrap.jsx
  gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
Labels: 🙆🏻‍♀️ 구현 완료, ♻️리팩토링

#292 🔀 Refactor/DetailPageDesign#289 [공고상세페이지 반응형 및 불필요한 코드 삭제]
  gongjakso/src/features/modal/ClickmyApply.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageProject.jsx
  gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
Labels: ♻️리팩토링

#295 🔀 Fix/DescriptionBox#294 [ 공고상세페이지 줄바꿈 반영 및 박스 사이즈 조절 ]
  gongjakso/src/features/modal/ApplyModal.styled.jsx
  gongjakso/src/pages/DetailPage/DetailPageContest.jsx
  gongjakso/src/pages/DetailPage/DetailPageStyled.jsx
  gongjakso/src/pages/ProfileRecruit/PdfUserApplicationStyled.jsx
  gongjakso/src/pages/TeamBox/TeamBoxStyled.jsx
Labels: 🐛버그 수정, ♻️리팩토링
